# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-21 18:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=1000)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('error_msg', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('content_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='error',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.ErrorGroup'),
        ),
        migrations.AddField(
            model_name='error',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
