# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-21 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='auth',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
