# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20170921_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='error',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
